---
- name: Debug task
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    message:
    sleep: 1

  tasks:
  - name: Sleep for some time
    ansible.builtin.pause:
      seconds: "{{ sleep }}"

  - name: Print debug message
    ansible.builtin.debug:
      msg: "{{ message }}"